apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          #image: 013958955750.dkr.ecr.ap-northeast-2.amazonaws.com/monolith-backend:22 
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mariadb://mariadb:3306/mydb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: "{{ .Values.mariadb.rootPassword }}"
      imagePullSecrets:
      - name: ecr-secret
