server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://mariadb.default.svc.cluster.local:3306/mydb
    username: root
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
