apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          #image: 013958955750.dkr.ecr.ap-northeast-2.amazonaws.com/monolith-frontend:22
        ports:
        - containerPort: {{ .Values.frontend.port }}
      imagePullSecrets:
      - name: ecr-secret
